---
services:
  owu-pipeline:
    image: ghcr.io/open-webui/pipelines:main
    hostname: owu-pipeline # Hostname in OpenWebui will be https://owu-pipeline:<PORT> | API KEY: 0p3n-w3bu!
    environment:
      RESET_PIPELINES_DIR: "true" # Default False, if set to true action will be taken. removing old python code
###      PIPELINES_REQUIREMENTS_PATH: # installation of requirements.
      PIPELINES_URLS: "https://github.com/open-webui/pipelines/blob/d4fca4c37c4b8603be7797245e749e9086f35130/examples/filters/langfuse_filter_pipeline.py" # pipelines download and installation.
    volumes:
      - pipelines:/app/pipelines
    ports:
      - target: 9099
        published: 9099
        protocol: tcp
        mode: overlay
    deploy:
      restart_policy:
          condition: any
          delay: 5s
          max_attempts: 3
    networks:
      - internal-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pipelines:
    driver: local

networks:
  internal-net:
    name: internal-net
    external: true
    driver: overlay