
services:
  openWebUI:
    hostname: openwebui
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
    ### Make sure this won't run if the backend and DB aren't working
        - chromadb
        - ollama
    volumes:
      - /data/open-webui/data:/app/backend/data # Backend Data
      - /data/material:/app/backend/data/docs # Documents to feed
      - /data/open-webui/static:/app/build/static # Static files
###      - /data/open-webui/frontend-build/build:/app/build ## Frontend Files
    environment:
      ENV: dev ##Enable some endpoints for development
      DATA_DIR: /app/backend/data ## Absolute path inside the container
      STATIC_DIR: /app/build/static ## Can set LOGO in here
###      FRONTEND_BUILD_DIR: /app/build ## Maybe Someday we do something here
      OLLAMA_BASE_URLS: http://ollama:11434
      CHROMA_HTTP_PORT: 8000
      CHROMA_HTTP_HOST: chromadb
      CHROMA_TENANT: default_tenant
      VECTOR_DB: chroma
      ENABLE_OPENAI_API: "False"
      WEBUI_NAME: Evil Corp AI
      CORS_ALLOW_ORIGIN: "*" # This is the current Default, will need to change before going live
      RAG_EMBEDDING_ENGINE: ollama
      RAG_EMBEDDING_MODEL: nomic-embed-text-v1.5
      RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE: "True"
      DOCS_DIR: ${DATA_DIR}/docs
    ports:
      - target: 8080
        published: 8080
        mode: bridge
    healthcheck:
      test: ["CMD-SHELL", "curl chromadb:8000/api/v1/heartbeat || exit 1"]
      interval: 120s
      retries: 2
      start_period: 5s
      timeout: 10s
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: "1G"
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    networks:
      - internal-net

  chromadb:
    hostname: chromadb
    image: chromadb/chroma:0.5.5 ##known issues with newer versions and compatibility  
    volumes:
      - /data/chromadb:/chroma/chroma
    environment:
      - REBUILD_HNSWLIB=TRUE
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE}
      - CHROMA_OTEL_COLLECTION_ENDPOINT=http://otel-collector:4317/
      - CHROMA_OTEL_EXPORTER_HEADERS=${CHROMA_OTEL_EXPORTER_HEADERS:-{}}
      - CHROMA_OTEL_SERVICE_NAME=chromadb
      - CHROMA_OTEL_GRANULARITY=${CHROMA_OTEL_GRANULARITY:-all}
    ports:
      - target: 8000
        published: 8000
        mode: bridge
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1Gib
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        ### Commenting out in favor of the health check on the main app
####    healthcheck: 
####      test: ["CMD-SHELL", "curl localhost:8000/api/v1/heartbeat || exit 1"]
####      interval: 30s
####      retries: 2
####      start_period: 5s
####      timeout: 10s
    networks:
      - internal-net

  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    ports:
      - target: 11434
        published: 11434
        mode: overlay
    deploy:
      resources:
###        limits:
###          cpus: '2.0'
###          memory: 8Gib
        reservations:
          cpus: '1.0'
          memory: 4Gib
###          generic_resources:
###            - discrete_resource_spec:
###                kind: "NVIDIA-GPU"
###                value: 1
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    volumes:
      - /data/ollama:/root/.ollama
    networks:
      - internal-net

volumes:
  open-webui-data:
    external: true
  chromadb-data:
    external: true
  ollama-data:
    external: true

networks:
  internal-net:
    name: internal-net
    external: true
    driver: overlay
